name: betwizz_app
description: A new Flutter project for Betwizz.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjusted based on typical modern Flutter setup

dependencies:
  flutter:
    sdk: flutter

  # Dependencies from PRD 5.2
  payfast_flutter: ^1.5.0
  agora_rtc_engine: ^6.0.0
  # firebase_ml_vision: ^4.0.0 # Removed, deprecated
  google_ml_kit_text_recognition: ^0.11.0 # For OCR
  flutter_secure_storage: ^8.0.0
  riverpod: ^2.0.0 # Assuming flutter_riverpod for Flutter specific bindings
  flutter_riverpod: ^2.4.0 # Adding flutter_riverpod explicitly
  fl_chart: ^0.55.0

  # Firebase Core - required for other Firebase packages
  firebase_core: ^2.20.0 # Example version, align with other firebase deps

  # Firebase Auth - from PRD 1.2
  firebase_auth: ^5.0.0 # PRD specified 5.0, ensure compatibility

  # Cloud Firestore
  cloud_firestore: ^4.17.0 # For user profile storage & other DB needs

  # For ZAR formatting - from PRD 6.1
  intl: ^0.19.0 # For NumberFormat

  # For Camera Preview - from PRD 7.1 (CameraPreview is part of camera package)
  camera: ^0.10.5+2 # Example version for camera package

  # For Rive animations - from PRD 7.1
  rive: ^0.11.12 # Example version for Rive

  # For video_player - from PRD 2.2
  video_player: ^2.7.0 # Example version

  # For flutter_secure_chat - from PRD 2.2 (Assuming this is a hypothetical package name)
  # As flutter_secure_chat 2.1 is not a known public package, I will comment it out.
  # If it's a private package, it would need to be hosted or path referenced.
  # flutter_secure_chat: ^2.1.0

  # For sportradar_flutter - from PRD 1.2 (Assuming this is a hypothetical package name)
  # sportradar_flutter: ^1.2.0

  # For PayFast API (payfast_plugin 2.0) - from PRD 1.2
  # The PRD lists payfast_plugin 2.0 and payfast_flutter 1.5.
  # I've used payfast_flutter as per section 5.2. If payfast_plugin is different, it needs clarification.

  # For AES256 encryption - from PRD 2.1 (Strategy Sharing) & PRD 6.1 (POPIA Compliance - Hive with AES)
  # A common package for this is encrypt.
  encrypt: ^5.0.1 # For AES encryption. To be used with local storage (e.g. Hive) for POPIA.

  # For Icons - usually included with cupertino_icons with Flutter
  cupertino_icons: ^1.0.2

  # For handling runtime permissions (e.g., camera, microphone for Agora)
  permission_handler: ^11.0.0 # Check pub.dev for latest version

  # For generating unique IDs (e.g., for chat messages)
  uuid: ^4.0.0 # Check pub.dev for latest version

  # For WebSocket communication
  web_socket_channel: ^2.4.0 # Check pub.dev for latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An example of adding fonts to your application:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
