import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
// import 'package:firebase_core/firebase_core.dart'; // Uncomment when Firebase is configured

import 'app.dart';
// import 'firebase_options.dart'; // Generated by FlutterFire CLI

void main() async {
  // Ensure Flutter bindings are initialized
  WidgetsFlutterBinding.ensureInitialized();

  // Placeholder for Firebase Initialization
  // try {
  //   await Firebase.initializeApp(
  //     options: DefaultFirebaseOptions.currentPlatform, // From firebase_options.dart
  //   );
  // } catch (e) {
  //   debugPrint("Firebase initialization failed: $e");
  //   // Handle initialization error, maybe show an error screen or retry
  // }

  // runApp() should be wrapped in a ProviderScope for Riverpod
  runApp(
    const ProviderScope(
      child: BetwizzApp(),
    ),
  );
}
